import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  gameSidebar: [
    {
      type: "doc",
      id: "games",
      label: "게임 목록",
    },
  ],
  musicSidebar: [
    {
      type: "category",
      label: "음악",
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "music",
        },
      ],
    },
  ],
  toySidebar: [
    {
      type: "category",
      label: "장난감",
      link: {
        type: "generated-index",
        slug: "toy/intro",
        description: "동방 프로젝트 관련 장난감과 도구들입니다.",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "toy",
        },
      ],
    },
  ],
};

export default sidebars;
