import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  gameSidebar: [
    {
      type: "category",
      label: "슈팅 게임",
      items: [
        {
          type: "autogenerated",
          dirName: "shooting_game",
        },
      ],
    },
    {
      type: "category",
      label: "대전 격투 게임",
      items: [
        {
          type: "autogenerated",
          dirName: "fighting_game",
        },
      ],
    },
    // Add other categories or items here if needed
  ],
  musicSidebar: [
    {
      type: "category",
      label: "음악",
      items: [
        {
          type: "autogenerated",
          dirName: "music",
        },
      ],
    },
  ],
};

export default sidebars;
