import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  gameSidebar: [
    {
      type: "category",
      label: "슈팅 게임",
      collapsed: true,
      link: {
        type: "generated-index",
        slug: "shooting_game/intro",
        description:
          "동방 프로젝트의 캐릭터들이 등장하는 슈팅 게임입니다. 각 게임의 상세 정보는 omake.txt 파일을 기준으로 작성되어 있습니다.",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "shooting_game",
        },
      ],
    },
    {
      type: "category",
      label: "대전 격투 게임",
      collapsed: true,
      link: {
        type: "generated-index",
        slug: "fighting_game/intro",
        description:
          "동방 프로젝트의 캐릭터들이 등장하는 대전 격투 게임입니다. 이 게임은 황혼프론티어에서 제작하였으며, 각 게임의 상세 정보는 omake.txt 파일을 기준으로 작성되어 있습니다.",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "fighting_game",
        },
      ],
    },
    // Add other categories or items here if needed
  ],
  musicSidebar: [
    {
      type: "category",
      label: "음악",
      link: {
        type: "generated-index",
        slug: "music/intro",
        description:
          "상하이 앨리스 환악단에서 제작한 동방 프로젝트의 음악입니다.",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "music",
        },
      ],
    },
  ],
  toySidebar: [
    {
      type: "category",
      label: "장난감",
      link: {
        type: "generated-index",
        slug: "toy/intro",
        description: "동방 프로젝트 관련 장난감과 도구들입니다.",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "toy",
        },
      ],
    },
  ],
};

export default sidebars;
