// 동방 투표 데이터 타입 정의
export interface TouhouCharacter {
  name_ja: string;
  name_en: string;
  rank_prev2: number | null;
  rank_prev: number | null;
  rank_now: number | null;
  points: number;
}

// 동방 투표 데이터 (15개만 포함)
export const TOUHOU_DATA: TouhouCharacter[] = [
  {
    name_ja: "古明地 こいし",
    name_en: "Koishi Komeiji",
    rank_prev2: 4.0,
    rank_prev: 4.0,
    rank_now: 1,
    points: 27688,
  },
  {
    name_ja: "霧雨 魔理沙",
    name_en: "Marisa Kirisame",
    rank_prev2: 1.0,
    rank_prev: 2.0,
    rank_now: 2,
    points: 27553,
  },
  {
    name_ja: "博麗 霊夢",
    name_en: "Reimu Hakurei",
    rank_prev2: 2.0,
    rank_prev: 1.0,
    rank_now: 3,
    points: 27408,
  },
  {
    name_ja: "フランドール・スカーレット",
    name_en: "Flandre Scarlet",
    rank_prev2: 3.0,
    rank_prev: 3.0,
    rank_now: 4,
    points: 23917,
  },
  {
    name_ja: "十六夜 咲夜",
    name_en: "Sakuya Izayoi",
    rank_prev2: 6.0,
    rank_prev: 6.0,
    rank_now: 5,
    points: 19804,
  },
  {
    name_ja: "レミリア・スカーレット",
    name_en: "Remilia Scarlet",
    rank_prev2: 7.0,
    rank_prev: 7.0,
    rank_now: 6,
    points: 19638,
  },
  {
    name_ja: "魂魄 妖夢",
    name_en: "Youmu Konpaku",
    rank_prev2: 5.0,
    rank_prev: 5.0,
    rank_now: 7,
    points: 18435,
  },
  {
    name_ja: "古明地 さとり",
    name_en: "Satori Komeiji",
    rank_prev2: 9.0,
    rank_prev: 8.0,
    rank_now: 8,
    points: 13504,
  },
  {
    name_ja: "藤原 妹紅",
    name_en: "Fujiwara no Mokou",
    rank_prev2: 8.0,
    rank_prev: 9.0,
    rank_now: 9,
    points: 12665,
  },
  {
    name_ja: "チルノ",
    name_en: "Cirno",
    rank_prev2: 15.0,
    rank_prev: 10.0,
    rank_now: 10,
    points: 12447,
  },
  {
    name_ja: "射命丸 文",
    name_en: "Aya Shameimaru",
    rank_prev2: 13.0,
    rank_prev: 13.0,
    rank_now: 11,
    points: 10133,
  },
  {
    name_ja: "西行寺 幽々子",
    name_en: "Yuyuko Saigyouji",
    rank_prev2: 10.0,
    rank_prev: 11.0,
    rank_now: 12,
    points: 9612,
  },
  {
    name_ja: "東風谷 早苗",
    name_en: "Sanae Kochiya",
    rank_prev2: 12.0,
    rank_prev: 14.0,
    rank_now: 13,
    points: 9426,
  },
  {
    name_ja: "アリス・マーガトロイド",
    name_en: "Alice Margatroid",
    rank_prev2: 11.0,
    rank_prev: 12.0,
    rank_now: 14,
    points: 9331,
  },
  {
    name_ja: "鈴仙・優曇華院・イナバ",
    name_en: "Reisen Udongein Inaba",
    rank_prev2: 14.0,
    rank_prev: 15.0,
    rank_now: 15,
    points: 8609,
  },
  {
    name_ja: "八雲 紫",
    name_en: "Yukari Yakumo",
    rank_prev2: 16.0,
    rank_prev: 16.0,
    rank_now: 16,
    points: 7376,
  },
  {
    name_ja: "紅 美鈴",
    name_en: "Hong Meiling",
    rank_prev2: 23.0,
    rank_prev: 18.0,
    rank_now: 17,
    points: 7315,
  },
  {
    name_ja: "パチュリー・ノーレッジ",
    name_en: "Patchouli Knowledge",
    rank_prev2: 18.0,
    rank_prev: 17.0,
    rank_now: 18,
    points: 7216,
  },
  {
    name_ja: "ルーミア",
    name_en: "Rumia",
    rank_prev2: 19.0,
    rank_prev: 21.0,
    rank_now: 19,
    points: 7062,
  },
  {
    name_ja: "秦 こころ",
    name_en: "Hata no Kokoro",
    rank_prev2: 21.0,
    rank_prev: 19.0,
    rank_now: 20,
    points: 6729,
  },
  {
    name_ja: "比那名居 天子",
    name_en: "Tenshi Hinanawi",
    rank_prev2: 17.0,
    rank_prev: 20.0,
    rank_now: 21,
    points: 6672,
  },
  {
    name_ja: "多々良 小傘",
    name_en: "Kogasa Tatara",
    rank_prev2: 22.0,
    rank_prev: 23.0,
    rank_now: 22,
    points: 6249,
  },
  {
    name_ja: "洩矢 諏訪子",
    name_en: "Suwako Moriya",
    rank_prev2: 20.0,
    rank_prev: 22.0,
    rank_now: 23,
    points: 5943,
  },
  {
    name_ja: "四季映姫・ヤマザナドゥ",
    name_en: "Eiki Shiki, Yamaxanadu",
    rank_prev2: 25.0,
    rank_prev: 25.0,
    rank_now: 24,
    points: 5524,
  },
  {
    name_ja: "蓬莱山 輝夜",
    name_en: "Kaguya Houraisan",
    rank_prev2: 34.0,
    rank_prev: 30.0,
    rank_now: 25,
    points: 5022,
  },
  {
    name_ja: "純狐",
    name_en: "Junko",
    rank_prev2: 28.0,
    rank_prev: 26.0,
    rank_now: 26,
    points: 4972,
  },
  {
    name_ja: "風見 幽香",
    name_en: "Yuuka Kazami",
    rank_prev2: 26.0,
    rank_prev: 24.0,
    rank_now: 27,
    points: 4959,
  },
  {
    name_ja: "八意 永琳",
    name_en: "Eirin Yagokoro",
    rank_prev2: 53.0,
    rank_prev: 37.0,
    rank_now: 28,
    points: 4889,
  },
  {
    name_ja: "伊吹 萃香",
    name_en: "Suika Ibuki",
    rank_prev2: 30.0,
    rank_prev: 27.0,
    rank_now: 29,
    points: 4733,
  },
  {
    name_ja: "犬走 椛",
    name_en: "Momiji Inubashiri",
    rank_prev2: 27.0,
    rank_prev: 28.0,
    rank_now: 30,
    points: 4621,
  },
  {
    name_ja: "八雲 藍",
    name_en: "Ran Yakumo",
    rank_prev2: 24.0,
    rank_prev: 29.0,
    rank_now: 31,
    points: 4325,
  },
  {
    name_ja: "霊烏路 空",
    name_en: "Utsuho Reiuji",
    rank_prev2: 33.0,
    rank_prev: 31.0,
    rank_now: 32,
    points: 4315,
  },
  {
    name_ja: "ヘカーティア・ラピスラズリ",
    name_en: "Hecatia Lapislazuli",
    rank_prev2: 38.0,
    rank_prev: 38.0,
    rank_now: 33,
    points: 4069,
  },
  {
    name_ja: "依神紫苑",
    name_en: "Shion Yorigami",
    rank_prev2: 32.0,
    rank_prev: 32.0,
    rank_now: 34,
    points: 4065,
  },
  {
    name_ja: "鬼人 正邪",
    name_en: "Seija Kijin",
    rank_prev2: 35.0,
    rank_prev: 35.0,
    rank_now: 35,
    points: 4035,
  },
  {
    name_ja: "豊聡耳 神子",
    name_en: "Toyosatomimi no Miko",
    rank_prev2: 31.0,
    rank_prev: 33.0,
    rank_now: 36,
    points: 3952,
  },
  {
    name_ja: "水橋 パルスィ",
    name_en: "Parsee Mizuhashi",
    rank_prev2: 37.0,
    rank_prev: 36.0,
    rank_now: 37,
    points: 3825,
  },
  {
    name_ja: "宇佐見 蓮子",
    name_en: "Renko Usami",
    rank_prev2: 41.0,
    rank_prev: 34.0,
    rank_now: 38,
    points: 3690,
  },
  {
    name_ja: "鍵山 雛",
    name_en: "Hina Kagiyama",
    rank_prev2: 45.0,
    rank_prev: 43.0,
    rank_now: 39,
    points: 3647,
  },
  {
    name_ja: "物部 布都",
    name_en: "Mononobe no Futo",
    rank_prev2: 39.0,
    rank_prev: 40.0,
    rank_now: 40,
    points: 3571,
  },
  {
    name_ja: "稀神 サグメ",
    name_en: "Sagume Kishin",
    rank_prev2: 36.0,
    rank_prev: 44.0,
    rank_now: 41,
    points: 3561,
  },
  {
    name_ja: "飯綱丸 龍",
    name_en: "Megumu Iizunamaru",
    rank_prev2: 66.0,
    rank_prev: 55.0,
    rank_now: 42,
    points: 3482,
  },
  {
    name_ja: "摩多羅隠岐奈",
    name_en: "Okina Matara",
    rank_prev2: 44.0,
    rank_prev: 45.0,
    rank_now: 43,
    points: 3430,
  },
  {
    name_ja: "河城 にとり",
    name_en: "Nitori Kawashiro",
    rank_prev2: 40.0,
    rank_prev: 41.0,
    rank_now: 44,
    points: 3262,
  },
  {
    name_ja: "茨木 華扇",
    name_en: "Kasen Ibaraki",
    rank_prev2: 43.0,
    rank_prev: 46.0,
    rank_now: 45,
    points: 3027,
  },
  {
    name_ja: "火焔猫 燐",
    name_en: "Rin Kaenbyou",
    rank_prev2: 42.0,
    rank_prev: 47.0,
    rank_now: 46,
    points: 2952,
  },
  {
    name_ja: "ミスティア・ローレライ",
    name_en: "Mystia Lorelei",
    rank_prev2: 63.0,
    rank_prev: 52.0,
    rank_now: 47,
    points: 2906,
  },
  {
    name_ja: "饕餮 尤魔",
    name_en: "Yuma Toutetsu",
    rank_prev2: 29.0,
    rank_prev: 42.0,
    rank_now: 48,
    points: 2886,
  },
  {
    name_ja: "魅魔",
    name_en: "Mima Revengeful Ghost",
    rank_prev2: 70.0,
    rank_prev: 56.0,
    rank_now: 49,
    points: 2860,
  },
  {
    name_ja: "聖 白蓮",
    name_en: "Byakuren Hijiri",
    rank_prev2: 48.0,
    rank_prev: 49.0,
    rank_now: 50,
    points: 2733,
  },
  {
    name_ja: "橙",
    name_en: "Chen",
    rank_prev2: 50.0,
    rank_prev: 51.0,
    rank_now: 51,
    points: 2726,
  },
  {
    name_ja: "上白沢 慧音",
    name_en: "Keine Kamishirasawa",
    rank_prev2: 55.0,
    rank_prev: 50.0,
    rank_now: 52,
    points: 2688,
  },
  {
    name_ja: "大妖精",
    name_en: "Daiyousei",
    rank_prev2: 61.0,
    rank_prev: 63.0,
    rank_now: 53,
    points: 2633,
  },
  {
    name_ja: "封獣 ぬえ",
    name_en: "Nue Houjuu",
    rank_prev2: 51.0,
    rank_prev: 53.0,
    rank_now: 54,
    points: 2581,
  },
  {
    name_ja: "マエリベリー・ハーン",
    name_en: "Maribel Hearn",
    rank_prev2: 54.0,
    rank_prev: 48.0,
    rank_now: 55,
    points: 2511,
  },
  {
    name_ja: "天弓 千亦",
    name_en: "Chimata Tenkyuu",
    rank_prev2: 64.0,
    rank_prev: 59.0,
    rank_now: 56,
    points: 2468,
  },
  {
    name_ja: "小悪魔",
    name_en: "Koakuma",
    rank_prev2: 57.0,
    rank_prev: 57.0,
    rank_now: 57,
    points: 2289,
  },
  {
    name_ja: "ナズーリン",
    name_en: "Nazrin",
    rank_prev2: 48.0,
    rank_prev: 54.0,
    rank_now: 58,
    points: 2156,
  },
  {
    name_ja: "ドレミー・スイート",
    name_en: "Doremy Sweet",
    rank_prev2: 56.0,
    rank_prev: 58.0,
    rank_now: 59,
    points: 2094,
  },
  {
    name_ja: "道神 馴子",
    name_en: "Nareko Michigami",
    rank_prev2: NaN,
    rank_prev: NaN,
    rank_now: 60,
    points: 2076,
  },
  {
    name_ja: "神綺",
    name_en: "Shinki",
    rank_prev2: 94.0,
    rank_prev: 67.0,
    rank_now: 61,
    points: 2055,
  },
  {
    name_ja: "埴安神 袿姫",
    name_en: "Keiki Haniyasushin",
    rank_prev2: 58.0,
    rank_prev: 66.0,
    rank_now: 62,
    points: 1916,
  },
  {
    name_ja: "リグル・ナイトバグ",
    name_en: "Wriggle Nightbug",
    rank_prev2: 87.0,
    rank_prev: 71.0,
    rank_now: 63,
    points: 1906,
  },
  {
    name_ja: "因幡 てゐ",
    name_en: "Tewi Inaba",
    rank_prev2: 67.0,
    rank_prev: 69.0,
    rank_now: 64,
    points: 1871,
  },
  {
    name_ja: "赤蛮奇",
    name_en: "Sekibanki",
    rank_prev2: 64.0,
    rank_prev: 64.0,
    rank_now: 65,
    points: 1860,
  },
  {
    name_ja: "菅牧 典",
    name_en: "Tsukasa Kudamaki",
    rank_prev2: 47.0,
    rank_prev: 61.0,
    rank_now: 66,
    points: 1848,
  },
  {
    name_ja: "村紗 水蜜",
    name_en: "Minamitsu Murasa",
    rank_prev2: 59.0,
    rank_prev: 65.0,
    rank_now: 67,
    points: 1832,
  },
  {
    name_ja: "霍 青娥",
    name_en: "Seiga Kaku",
    rank_prev2: 60.0,
    rank_prev: 62.0,
    rank_now: 68,
    points: 1820,
  },
  {
    name_ja: "八坂 神奈子",
    name_en: "Kanako Yasaka",
    rank_prev2: 76.0,
    rank_prev: 74.0,
    rank_now: 69,
    points: 1734,
  },
  {
    name_ja: "クラウンピース",
    name_en: "Clownpiece",
    rank_prev2: 62.0,
    rank_prev: 60.0,
    rank_now: 70,
    points: 1724,
  },
  {
    name_ja: "リリーホワイト",
    name_en: "Lily White",
    rank_prev2: 90.0,
    rank_prev: 79.0,
    rank_now: 71,
    points: 1692,
  },
  {
    name_ja: "本居 小鈴",
    name_en: "Kosuzu Motoori",
    rank_prev2: 72.0,
    rank_prev: 72.0,
    rank_now: 72,
    points: 1657,
  },
  {
    name_ja: "綿月 豊姫",
    name_en: "Watatsuki no Toyohime",
    rank_prev2: 115.0,
    rank_prev: 119.0,
    rank_now: 73,
    points: 1629,
  },
  {
    name_ja: "依神女苑",
    name_en: "Joon Yorigami",
    rank_prev2: 76.0,
    rank_prev: 68.0,
    rank_now: 74,
    points: 1575,
  },
  {
    name_ja: "小野塚 小町",
    name_en: "Komachi Onozuka",
    rank_prev2: 88.0,
    rank_prev: 76.0,
    rank_now: 75,
    points: 1555,
  },
  {
    name_ja: "永江 衣玖",
    name_en: "Iku Nagae",
    rank_prev2: 73.0,
    rank_prev: 75.0,
    rank_now: 76,
    points: 1554,
  },
  {
    name_ja: "姫海棠 はたて",
    name_en: "Hatate Himekaidou",
    rank_prev2: 84.0,
    rank_prev: 78.0,
    rank_now: 77,
    points: 1527,
  },
  {
    name_ja: "二ッ岩 マミゾウ",
    name_en: "Mamizou Futatsuiwa",
    rank_prev2: 75.0,
    rank_prev: 73.0,
    rank_now: 78,
    points: 1513,
  },
  {
    name_ja: "稗田 阿求",
    name_en: "Hieda no Akyuu",
    rank_prev2: 86.0,
    rank_prev: 39.0,
    rank_now: 79,
    points: 1499,
  },
  {
    name_ja: "幻月",
    name_en: "Gengetsu",
    rank_prev2: 118.0,
    rank_prev: 102.0,
    rank_now: 80,
    points: 1481,
  },
  {
    name_ja: "吉弔 八千慧",
    name_en: "Yachie Kicchou",
    rank_prev2: 46.0,
    rank_prev: 70.0,
    rank_now: 81,
    points: 1478,
  },
  {
    name_ja: "森近 霖之助",
    name_en: "Rinnosuke Morichika",
    rank_prev2: 83.0,
    rank_prev: 77.0,
    rank_now: 82,
    points: 1436,
  },
  {
    name_ja: "今泉 影狼",
    name_en: "Kagerou Imaizumi",
    rank_prev2: 69.0,
    rank_prev: 84.0,
    rank_now: 83,
    points: 1394,
  },
  {
    name_ja: "星熊 勇儀",
    name_en: "Yuugi Hoshiguma",
    rank_prev2: 82.0,
    rank_prev: 80.0,
    rank_now: 84,
    points: 1360,
  },
  {
    name_ja: "宇佐見 菫子",
    name_en: "Sumireko Usami",
    rank_prev2: 80.0,
    rank_prev: 82.0,
    rank_now: 85,
    points: 1346,
  },
  {
    name_ja: "庭渡 久侘歌",
    name_en: "Kutaka Niwatari",
    rank_prev2: 79.0,
    rank_prev: 83.0,
    rank_now: 86,
    points: 1324,
  },
  {
    name_ja: "少名 針妙丸",
    name_en: "Shinmyoumaru Sukuna",
    rank_prev2: 91.0,
    rank_prev: 89.0,
    rank_now: 87,
    points: 1287,
  },
  {
    name_ja: "蘇我 屠自古",
    name_en: "Soga no Tojiko",
    rank_prev2: 85.0,
    rank_prev: 86.0,
    rank_now: 88,
    points: 1285,
  },
  {
    name_ja: "奥野田 美宵",
    name_en: "Miyoi Okunoda",
    rank_prev2: 92.0,
    rank_prev: 88.0,
    rank_now: 89,
    points: 1229,
  },
  {
    name_ja: "岡崎 夢美",
    name_en: "Yumemi Okazaki",
    rank_prev2: 103.0,
    rank_prev: 94.0,
    rank_now: 90,
    points: 1221,
  },
  {
    name_ja: "宮出口瑞霊",
    name_en: "Mizuchi Miyadeguchi",
    rank_prev2: 136.0,
    rank_prev: 118.0,
    rank_now: 91,
    points: 1207,
  },
  {
    name_ja: "堀川 雷鼓",
    name_en: "Raiko Horikawa",
    rank_prev2: 99.0,
    rank_prev: 95.0,
    rank_now: 92,
    points: 1199,
  },
  {
    name_ja: "メディスン・メランコリー",
    name_en: "Medicine Melancholy",
    rank_prev2: 96.0,
    rank_prev: 93.0,
    rank_now: 93,
    points: 1132,
  },
  {
    name_ja: "綿月 依姫",
    name_en: "Watatsuki no Yorihime",
    rank_prev2: 97.0,
    rank_prev: 96.0,
    rank_now: 94,
    points: 1128,
  },
  {
    name_ja: "高麗野あうん",
    name_en: "Aunn Komano",
    rank_prev2: 93.0,
    rank_prev: 85.0,
    rank_now: 95,
    points: 1104,
  },
  {
    name_ja: "豫母都 日狭美",
    name_en: "Hisami Yomotsu",
    rank_prev2: 52.0,
    rank_prev: 81.0,
    rank_now: 96,
    points: 1096,
  },
  {
    name_ja: "ルナチャイルド",
    name_en: "Luna Child",
    rank_prev2: 111.0,
    rank_prev: 103.0,
    rank_now: 97,
    points: 1046,
  },
  {
    name_ja: "宮古 芳香",
    name_en: "Yoshika Miyako",
    rank_prev2: 97.0,
    rank_prev: 92.0,
    rank_now: 98,
    points: 1039,
  },
  {
    name_ja: "わかさぎ姫",
    name_en: "Wakasagihime",
    rank_prev2: 105.0,
    rank_prev: 104.0,
    rank_now: 99,
    points: 1032,
  },
  {
    name_ja: "レティ・ホワイトロック",
    name_en: "Letty Whiterock",
    rank_prev2: 106.0,
    rank_prev: 91.0,
    rank_now: 100,
    points: 983,
  },
  {
    name_ja: "妖精（メイド妖精・ひまわり妖精 他）",
    name_en: "Fairy (Fairy Maids, Sunflower Fairy etc.)",
    rank_prev2: 166.0,
    rank_prev: 171.0,
    rank_now: 101,
    points: 971,
  },
  {
    name_ja: "姫虫 百々世",
    name_en: "Momoyo Himemushi",
    rank_prev2: 101.0,
    rank_prev: 98.0,
    rank_now: 102,
    points: 970,
  },
  {
    name_ja: "ルナサ・プリズムリバー",
    name_en: "Lunasa Prismriver",
    rank_prev2: 89.0,
    rank_prev: 90.0,
    rank_now: 103,
    points: 969,
  },
  {
    name_ja: "日白 残無",
    name_en: "Zanmu Nippaku",
    rank_prev2: 68.0,
    rank_prev: 87.0,
    rank_now: 103,
    points: 969,
  },
  {
    name_ja: "先代巫女",
    name_en: "Previous Hakurei Shrine Maiden",
    rank_prev2: NaN,
    rank_prev: NaN,
    rank_now: 105,
    points: 945,
  },
  {
    name_ja: "秋 穣子",
    name_en: "Minoriko Aki",
    rank_prev2: 100.0,
    rank_prev: 99.0,
    rank_now: 106,
    points: 944,
  },
  {
    name_ja: "秋 静葉",
    name_en: "Shizuha Aki",
    rank_prev2: 95.0,
    rank_prev: 101.0,
    rank_now: 107,
    points: 937,
  },
  {
    name_ja: "夢月",
    name_en: "Mugetsu",
    rank_prev2: 134.0,
    rank_prev: 120.0,
    rank_now: 108,
    points: 912,
  },
  {
    name_ja: "寅丸 星",
    name_en: "Shou Toramaru",
    rank_prev2: 104.0,
    rank_prev: 105.0,
    rank_now: 109,
    points: 879,
  },
  {
    name_ja: "幽谷 響子",
    name_en: "Kyouko Kasodani",
    rank_prev2: 110.0,
    rank_prev: 112.0,
    rank_now: 110,
    points: 864,
  },
  {
    name_ja: "天火人 ちやり",
    name_en: "Chiyari Tenkajin",
    rank_prev2: 74.0,
    rank_prev: 97.0,
    rank_now: 111,
    points: 858,
  },
  {
    name_ja: "驪駒 早鬼",
    name_en: "Saki Kurokoma",
    rank_prev2: 81.0,
    rank_prev: 100.0,
    rank_now: 112,
    points: 849,
  },
  {
    name_ja: "黒谷 ヤマメ",
    name_en: "Yamame Kurodani",
    rank_prev2: 112.0,
    rank_prev: 108.0,
    rank_now: 113,
    points: 822,
  },
  {
    name_ja: "スターサファイア",
    name_en: "Star Sapphire",
    rank_prev2: 108.0,
    rank_prev: 106.0,
    rank_now: 114,
    points: 816,
  },
  {
    name_ja: "蓬莱人形ジャケットイラストの娘",
    name_en: "The girl on the Houral Doll jacket",
    rank_prev2: 125.0,
    rank_prev: 114.0,
    rank_now: 115,
    points: 772,
  },
  {
    name_ja: "サニーミルク",
    name_en: "Sunny Milk",
    rank_prev2: 121.0,
    rank_prev: 113.0,
    rank_now: 116,
    points: 753,
  },
  {
    name_ja: "清蘭",
    name_en: "Seiran",
    rank_prev2: 102.0,
    rank_prev: 107.0,
    rank_now: 117,
    points: 706,
  },
  {
    name_ja: "雲居 一輪",
    name_en: "Ichirin Kumoi",
    rank_prev2: 124.0,
    rank_prev: 123.0,
    rank_now: 118,
    points: 704,
  },
  {
    name_ja: "C62サークルカットの娘",
    name_en: "The girl on the C62 circle cut for Comiket catalog",
    rank_prev2: NaN,
    rank_prev: 126.0,
    rank_now: 119,
    points: 695,
  },
  {
    name_ja: "杖刀偶 磨弓",
    name_en: "Mayumi Joutouguu",
    rank_prev2: 107.0,
    rank_prev: 109.0,
    rank_now: 120,
    points: 671,
  },
  {
    name_ja: "豪徳寺 ミケ",
    name_en: "Mike Goutokuji",
    rank_prev2: 116.0,
    rank_prev: 124.0,
    rank_now: 121,
    points: 660,
  },
  {
    name_ja: "カナ・アナベラル",
    name_en: "Kana Anaberal",
    rank_prev2: 130.0,
    rank_prev: 130.0,
    rank_now: 122,
    points: 648,
  },
  {
    name_ja: "丁礼田舞",
    name_en: "Mai Teireida",
    rank_prev2: 114.0,
    rank_prev: 115.0,
    rank_now: 123,
    points: 647,
  },
  {
    name_ja: "九十九 弁々",
    name_en: "Benben Tsukumo",
    rank_prev2: 123.0,
    rank_prev: 127.0,
    rank_now: 124,
    points: 642,
  },
  {
    name_ja: "メルラン・プリズムリバー",
    name_en: "Merlin Prismriver",
    rank_prev2: 113.0,
    rank_prev: 116.0,
    rank_now: 125,
    points: 634,
  },
  {
    name_ja: "アリスの人形（上海、蓬莱、大江戸 他）",
    name_en: "Alice's dolls (Shanghai, Horai, Oedo, etc.)",
    rank_prev2: 117.0,
    rank_prev: 117.0,
    rank_now: 126,
    points: 591,
  },
  {
    name_ja: "エタニティラルバ",
    name_en: "Eternity Larva",
    rank_prev2: 128.0,
    rank_prev: 122.0,
    rank_now: 127,
    points: 586,
  },
  {
    name_ja: "三頭 慧ノ子",
    name_en: "Enoko Mitsugashira",
    rank_prev2: 71.0,
    rank_prev: 111.0,
    rank_now: 128,
    points: 561,
  },
  {
    name_ja: "爾子田里乃",
    name_en: "Satono Nishida",
    rank_prev2: 126.0,
    rank_prev: 129.0,
    rank_now: 129,
    points: 534,
  },
  {
    name_ja: "くるみ",
    name_en: "Kurumi",
    rank_prev2: 140.0,
    rank_prev: 146.0,
    rank_now: 130,
    points: 520,
  },
  {
    name_ja: "影華扇（断善修悪の怪腕 - 茨木童子の腕）",
    name_en: "Kasen's arm",
    rank_prev2: 151.0,
    rank_prev: 139.0,
    rank_now: 131,
    points: 518,
  },
  {
    name_ja: "リリカ・プリズムリバー",
    name_en: "Lyrica Prismriver",
    rank_prev2: 119.0,
    rank_prev: 125.0,
    rank_now: 132,
    points: 513,
  },
  {
    name_ja: "封獣 チミ",
    name_en: "Chimi Houju",
    rank_prev2: NaN,
    rank_prev: NaN,
    rank_now: 133,
    points: 511,
  },
  {
    name_ja: "名無しの本読み妖怪",
    name_en: "Unnamed Book-Reading Youkai",
    rank_prev2: 122.0,
    rank_prev: 128.0,
    rank_now: 134,
    points: 503,
  },
  {
    name_ja: "夢子",
    name_en: "Yumeko",
    rank_prev2: 133.0,
    rank_prev: 135.0,
    rank_now: 135,
    points: 482,
  },
  {
    name_ja: "孫 美天",
    name_en: "Biten Son",
    rank_prev2: 78.0,
    rank_prev: 110.0,
    rank_now: 136,
    points: 461,
  },
  {
    name_ja: "鈴瑚",
    name_en: "Ringo",
    rank_prev2: 129.0,
    rank_prev: 132.0,
    rank_now: 137,
    points: 442,
  },
  {
    name_ja: "レイセン",
    name_en: "Reisen",
    rank_prev2: 127.0,
    rank_prev: 131.0,
    rank_now: 138,
    points: 424,
  },
  {
    name_ja: "北白河 ちゆり",
    name_en: "Chiyuri Kitashirakawa",
    rank_prev2: 142.0,
    rank_prev: 145.0,
    rank_now: 139,
    points: 418,
  },
  {
    name_ja: "易者",
    name_en: "The Fortune-teller",
    rank_prev2: 119.0,
    rank_prev: 121.0,
    rank_now: 140,
    points: 415,
  },
  {
    name_ja: "坂田ネムノ",
    name_en: "Nemuno Sakata",
    rank_prev2: 148.0,
    rank_prev: 153.0,
    rank_now: 141,
    points: 405,
  },
  {
    name_ja: "サリエル",
    name_en: "Sariel Angel of Death",
    rank_prev2: 132.0,
    rank_prev: 133.0,
    rank_now: 142,
    points: 403,
  },
  {
    name_ja: "矢田寺成美",
    name_en: "Narumi Yatadera",
    rank_prev2: 131.0,
    rank_prev: 134.0,
    rank_now: 143,
    points: 380,
  },
  {
    name_ja: "九十九 八橋",
    name_en: "Yatsuhashi Tsukumo",
    rank_prev2: 135.0,
    rank_prev: 136.0,
    rank_now: 144,
    points: 379,
  },
  {
    name_ja: "戎 瓔花",
    name_en: "Eika Ebisu",
    rank_prev2: 143.0,
    rank_prev: 139.0,
    rank_now: 145,
    points: 362,
  },
  {
    name_ja: "山城 たかね",
    name_en: "Takane Yamashiro",
    rank_prev2: 139.0,
    rank_prev: 137.0,
    rank_now: 146,
    points: 361,
  },
  {
    name_ja: "エレン",
    name_en: "Ellen",
    rank_prev2: 146.0,
    rank_prev: 150.0,
    rank_now: 147,
    points: 350,
  },
  {
    name_ja: "玉造 魅須丸",
    name_en: "Misumaru Tamatsukuri",
    rank_prev2: 140.0,
    rank_prev: 143.0,
    rank_now: 148,
    points: 329,
  },
  {
    name_ja: "エリー",
    name_en: "Elly",
    rank_prev2: 154.0,
    rank_prev: 144.0,
    rank_now: 149,
    points: 326,
  },
  {
    name_ja: "エリス",
    name_en: "Elis Innocent Devil",
    rank_prev2: 145.0,
    rank_prev: 157.0,
    rank_now: 150,
    points: 318,
  },
  {
    name_ja: "キスメ",
    name_en: "Kisume",
    rank_prev2: 137.0,
    rank_prev: 138.0,
    rank_now: 151,
    points: 313,
  },
  {
    name_ja: "駒草 山如",
    name_en: "Sannyo Komakusa",
    rank_prev2: 109.0,
    rank_prev: 141.0,
    rank_now: 152,
    points: 278,
  },
  {
    name_ja: "マイ",
    name_en: "Mai",
    rank_prev2: 157.0,
    rank_prev: 147.0,
    rank_now: 153,
    points: 277,
  },
  {
    name_ja: "コンガラ",
    name_en: "Konngara Astral Knight",
    rank_prev2: 150.0,
    rank_prev: 155.0,
    rank_now: 154,
    points: 272,
  },
  {
    name_ja: "魂魄 妖忌",
    name_en: "Youki Konpaku",
    rank_prev2: 143.0,
    rank_prev: 148.0,
    rank_now: 155,
    points: 264,
  },
  {
    name_ja: "ユキ",
    name_en: "Yuki",
    rank_prev2: 162.0,
    rank_prev: 156.0,
    rank_now: 156,
    points: 256,
  },
  {
    name_ja: "るーこと",
    name_en: "Ruukoto",
    rank_prev2: 161.0,
    rank_prev: 164.0,
    rank_now: 157,
    points: 248,
  },
  {
    name_ja: "蓬莱人形レーベルイラストの娘",
    name_en: "The girl on the Houral Doll label",
    rank_prev2: 158.0,
    rank_prev: 149.0,
    rank_now: 158,
    points: 241,
  },
  {
    name_ja: "牛崎 潤美",
    name_en: "Urumi Ushizaki",
    rank_prev2: 147.0,
    rank_prev: 152.0,
    rank_now: 159,
    points: 240,
  },
  {
    name_ja: "小兎姫",
    name_en: "Kotohime",
    rank_prev2: 149.0,
    rank_prev: 154.0,
    rank_now: 160,
    points: 224,
  },
  {
    name_ja: "オレンジ",
    name_en: "Orange",
    rank_prev2: 178.0,
    rank_prev: 173.0,
    rank_now: 161,
    points: 222,
  },
  {
    name_ja: "明羅",
    name_en: "Meira",
    rank_prev2: 155.0,
    rank_prev: 142.0,
    rank_now: 162,
    points: 217,
  },
  {
    name_ja: "塵塚 ウバメ",
    name_en: "Ubame Chirizuka",
    rank_prev2: NaN,
    rank_prev: NaN,
    rank_now: 163,
    points: 200,
  },
  {
    name_ja: "里香",
    name_en: "Rika",
    rank_prev2: 163.0,
    rank_prev: 161.0,
    rank_now: 164,
    points: 192,
  },
  {
    name_ja: "朝倉 理香子",
    name_en: "Rikako Asakura",
    rank_prev2: 164.0,
    rank_prev: 168.0,
    rank_now: 165,
    points: 178,
  },
  {
    name_ja: "抗鬱薬おじさん",
    name_en: "antidepressant uncle",
    rank_prev2: 137.0,
    rank_prev: 151.0,
    rank_now: 166,
    points: 172,
  },
  {
    name_ja: "ユウゲンマガン",
    name_en: "YuugenMagan Evil Eyes",
    rank_prev2: 170.0,
    rank_prev: 165.0,
    rank_now: 167,
    points: 170,
  },
  {
    name_ja: "雲山",
    name_en: "Unzan",
    rank_prev2: 156.0,
    rank_prev: 158.0,
    rank_now: 168,
    points: 166,
  },
  {
    name_ja: "玄爺",
    name_en: "Genjii",
    rank_prev2: 167.0,
    rank_prev: 166.0,
    rank_now: 169,
    points: 162,
  },
  {
    name_ja: "シンギョク",
    name_en: "SinGyoku Gatekeeper",
    rank_prev2: 174.0,
    rank_prev: 170.0,
    rank_now: 170,
    points: 154,
  },
  {
    name_ja: "レイラ・プリズムリバー",
    name_en: "Leila Prismriver",
    rank_prev2: 160.0,
    rank_prev: 160.0,
    rank_now: 171,
    points: 144,
  },
  {
    name_ja: "UFO（赤・青・緑、その他）",
    name_en: "Undefined Fantastic Object（Red, Blue, Green etc.)",
    rank_prev2: 165.0,
    rank_prev: 167.0,
    rank_now: 171,
    points: 144,
  },
  {
    name_ja: "毛玉",
    name_en: "Kedama",
    rank_prev2: 152.0,
    rank_prev: 159.0,
    rank_now: 173,
    points: 127,
  },
  {
    name_ja: "大ナマズ",
    name_en: "Giant Catfish",
    rank_prev2: 159.0,
    rank_prev: 162.0,
    rank_now: 174,
    points: 119,
  },
  {
    name_ja: "カワウソ霊",
    name_en: "Otter Spirit",
    rank_prev2: 153.0,
    rank_prev: 163.0,
    rank_now: 174,
    points: 119,
  },
  {
    name_ja: "ルイズ",
    name_en: "Louise",
    rank_prev2: 168.0,
    rank_prev: 169.0,
    rank_now: 176,
    points: 108,
  },
  {
    name_ja: "旧作名無し中ボス",
    name_en: "Old work nameless middle boss",
    rank_prev2: 173.0,
    rank_prev: 182.0,
    rank_now: 177,
    points: 89,
  },
  {
    name_ja: "サラ",
    name_en: "Sara",
    rank_prev2: 170.0,
    rank_prev: 181.0,
    rank_now: 178,
    points: 87,
  },
  {
    name_ja: "ツチノコ",
    name_en: "Tsuchinoko",
    rank_prev2: 177.0,
    rank_prev: 177.0,
    rank_now: 179,
    points: 85,
  },
  {
    name_ja: "核熱造神ヒソウテンソク",
    name_en: "Hisoutensoku",
    rank_prev2: 168.0,
    rank_prev: 172.0,
    rank_now: 180,
    points: 79,
  },
  {
    name_ja: "キクリ",
    name_en: "Kikuri Hellish Moon",
    rank_prev2: 183.0,
    rank_prev: 184.0,
    rank_now: 181,
    points: 77,
  },
  {
    name_ja: "鯢呑亭の常連",
    name_en: "Regular customers of the Guidon pub",
    rank_prev2: 181.0,
    rank_prev: 180.0,
    rank_now: 182,
    points: 74,
  },
  {
    name_ja: "ミミちゃん",
    name_en: "Mimi-Chan",
    rank_prev2: 172.0,
    rank_prev: 175.0,
    rank_now: 183,
    points: 73,
  },
  {
    name_ja: "兎（玉兎、永遠亭の妖怪兎 他）",
    name_en: "Rabbits (Moon Rabbit, Eientei rabbits etc.)",
    rank_prev2: 187.0,
    rank_prev: 183.0,
    rank_now: 184,
    points: 72,
  },
  {
    name_ja: "カラス（地獄鴉、紫・文の使い魔 他）",
    name_en: "Crow, Raven (Hell ravens, Yukari's and Aya's familiar etc.)",
    rank_prev2: 175.0,
    rank_prev: 173.0,
    rank_now: 185,
    points: 69,
  },
  {
    name_ja: "嫦娥",
    name_en: "Chang'e",
    rank_prev2: 179.0,
    rank_prev: 176.0,
    rank_now: 186,
    points: 65,
  },
  {
    name_ja: "なめえもん",
    name_en: "Nameemon",
    rank_prev2: 180.0,
    rank_prev: 179.0,
    rank_now: 187,
    points: 62,
  },
  {
    name_ja: "チュパカブラ",
    name_en: "Chupacabra",
    rank_prev2: 176.0,
    rank_prev: 177.0,
    rank_now: 188,
    points: 60,
  },
  {
    name_ja: "華扇の動物（久米、竿打、雷獣、彭祖、人面犬 他）",
    name_en: "Kasen's animals (Kume, Kanda, Raijuu, Houso, Jinmenken etc.)",
    rank_prev2: 182.0,
    rank_prev: 188.0,
    rank_now: 189,
    points: 55,
  },
  {
    name_ja: "岩笠",
    name_en: "Iwakasa",
    rank_prev2: 201.0,
    rank_prev: 195.0,
    rank_now: 190,
    points: 53,
  },
  {
    name_ja: "狐（妖怪狐、狐の子他）",
    name_en: "Kitsune (youkai kitsune, little fox etc.)",
    rank_prev2: 188.0,
    rank_prev: 185.0,
    rank_now: 191,
    points: 48,
  },
  {
    name_ja: "ホフゴブリン",
    name_en: "Hobgoblin",
    rank_prev2: 190.0,
    rank_prev: 192.0,
    rank_now: 192,
    points: 44,
  },
  {
    name_ja: "里の人間（文花帖、求聞史紀、鈴奈庵などで登場した人間）",
    name_en:
      "Village human (Humans who appeared in Bunkachou, Fumiki Komon, Suzunaan, etc.)",
    rank_prev2: 189.0,
    rank_prev: 194.0,
    rank_now: 192,
    points: 44,
  },
  {
    name_ja: "オオカミ霊",
    name_en: "Wolf Spirit",
    rank_prev2: 183.0,
    rank_prev: 190.0,
    rank_now: 194,
    points: 43,
  },
  {
    name_ja: "龍（子龍、邪龍 他）",
    name_en: "Dragon (small Dragon, Evil Dragon etc.)",
    rank_prev2: 191.0,
    rank_prev: 189.0,
    rank_now: 195,
    points: 38,
  },
  {
    name_ja: "河童（山童含む）",
    name_en: "Kappa (include Yamawaro)",
    rank_prev2: 185.0,
    rank_prev: 186.0,
    rank_now: 196,
    points: 36,
  },
  {
    name_ja: "万歳楽",
    name_en: "Manzairaku",
    rank_prev2: 195.0,
    rank_prev: 197.0,
    rank_now: 197,
    points: 35,
  },
  {
    name_ja: "天狗（香霖堂の天狗、大天狗 他）",
    name_en: "Tengu (Kourindou Tengu, Great Tengu etc.)",
    rank_prev2: 206.0,
    rank_prev: 187.0,
    rank_now: 198,
    points: 30,
  },
  {
    name_ja: "命蓮",
    name_en: "Myouren Hijiri",
    rank_prev2: 198.0,
    rank_prev: 196.0,
    rank_now: 199,
    points: 29,
  },
  {
    name_ja: "ケセランパサラン",
    name_en: "Kesaran Pasaran",
    rank_prev2: 201.0,
    rank_prev: 197.0,
    rank_now: 200,
    points: 28,
  },
  {
    name_ja: "都市伝説の怪異（お菊さん、八尺さま 他）",
    name_en: "Urban legend (Okiku-san, Hasshaku-sama, etc.)",
    rank_prev2: 194.0,
    rank_prev: 203.0,
    rank_now: 201,
    points: 27,
  },
  {
    name_ja: "仙台四郎（福の神）",
    name_en: "Shirou Sendai",
    rank_prev2: 207.0,
    rank_prev: 209.0,
    rank_now: 202,
    points: 26,
  },
  {
    name_ja: "神降ろしの神霊（天照、伊豆能売 他）",
    name_en: "Haunted spirit (Amaterasu, Izunome, etc.)",
    rank_prev2: 204.0,
    rank_prev: 193.0,
    rank_now: 202,
    points: 26,
  },
  {
    name_ja: "幽霊（怨霊、神霊、化け化け含む）",
    name_en: "Phantom (Vengeful spirit, Divine Spirit, include Bakebake)",
    rank_prev2: 193.0,
    rank_prev: 199.0,
    rank_now: 204,
    points: 23,
  },
  {
    name_ja: "オオワシ霊",
    name_en: "Eagle Spirit",
    rank_prev2: 185.0,
    rank_prev: 190.0,
    rank_now: 205,
    points: 22,
  },
  {
    name_ja: "鯢呑亭の店主",
    name_en: "The owner of the Geidon pub",
    rank_prev2: 197.0,
    rank_prev: 205.0,
    rank_now: 205,
    points: 22,
  },
  {
    name_ja: "木花咲耶姫",
    name_en: "Konohana-Sakuyahime",
    rank_prev2: 196.0,
    rank_prev: 202.0,
    rank_now: 207,
    points: 20,
  },
  {
    name_ja: "塩屋敷の旦那",
    name_en: "master of salt mansion",
    rank_prev2: 205.0,
    rank_prev: 216.0,
    rank_now: 207,
    points: 20,
  },
  {
    name_ja: "毘沙門天",
    name_en: "Bishamonten",
    rank_prev2: 212.0,
    rank_prev: 211.0,
    rank_now: 209,
    points: 19,
  },
  {
    name_ja: "酒虫",
    name_en: "Shuchuu",
    rank_prev2: 198.0,
    rank_prev: 206.0,
    rank_now: 209,
    points: 19,
  },
  {
    name_ja: "月の都の門番",
    name_en: "Gateguards of the Lunar Capital",
    rank_prev2: 207.0,
    rank_prev: 208.0,
    rank_now: 209,
    points: 19,
  },
  {
    name_ja: "ライカ",
    name_en: "Laika",
    rank_prev2: 191.0,
    rank_prev: 199.0,
    rank_now: 212,
    points: 18,
  },
  {
    name_ja: "水江浦島子",
    name_en: "Mizue no Uranoshimako",
    rank_prev2: 216.0,
    rank_prev: 199.0,
    rank_now: 213,
    points: 17,
  },
  {
    name_ja: "ウワバミ",
    name_en: "Uwabami (large snake)",
    rank_prev2: 201.0,
    rank_prev: 211.0,
    rank_now: 214,
    points: 16,
  },
  {
    name_ja: "沓頬",
    name_en: "Kutsutsura",
    rank_prev2: 214.0,
    rank_prev: 217.0,
    rank_now: 215,
    points: 14,
  },
  {
    name_ja: "狸（化け狸、野鉄砲他）",
    name_en: "Tanuki (Bake-danuki, Nodeppou etc.)",
    rank_prev2: 207.0,
    rank_prev: 214.0,
    rank_now: 216,
    points: 13,
  },
  {
    name_ja: "座敷童",
    name_en: "Zashiki-warashi",
    rank_prev2: 207.0,
    rank_prev: 203.0,
    rank_now: 217,
    points: 11,
  },
  {
    name_ja: "運松",
    name_en: "Unshou",
    rank_prev2: 211.0,
    rank_prev: 210.0,
    rank_now: 218,
    points: 10,
  },
  {
    name_ja: "ヤマネ",
    name_en: "Yamane",
    rank_prev2: 212.0,
    rank_prev: 211.0,
    rank_now: 218,
    points: 10,
  },
  {
    name_ja: "小鈴の両親",
    name_en: "Kosuzu's parents",
    rank_prev2: 198.0,
    rank_prev: 206.0,
    rank_now: 218,
    points: 10,
  },
  {
    name_ja: "煙々羅",
    name_en: "Enenra",
    rank_prev2: 214.0,
    rank_prev: 215.0,
    rank_now: 221,
    points: 3,
  },
];
